### ISSUE TITLE
How to issue token for a particular app in assertion flow? And refresh this token.

### ISSUE THREAD

**Issue by StarWar** [doorkeeper-gem/doorkeeper-grants_assertion#11]
Currently I'm using facebook token to issue access_token and it works without passing client_id and client_secret.
I want to issue token only if correct client_id and client_secret is provided. And refreshing token also doesn't work when client_id and secret provided.

**Comment by tute** [comment]
This repository is in need of maintainer. :-|

**Comment by StarWar** [comment]
**refresh token works without client id and secret when using assertion grant flow. **

Is this the way it is intended OR renewing access token should require client_id and secret also. currently it's working without client_id and client_secret when the access_token is generated using assertion grant flow.

**Comment by NuckChorris** [comment]
According to RFC7521, a client secret is not needed and a client id is optional:

>Authentication of the client is optional, as described in Section 3.2.1 of OAuth 2.0 [RFC6749], and consequently, the "client_id" is only needed when a form of client authentication that relies on the parameter is used.

So this behavior is correct for the most part.  The spec does say the following, which I believe differs from the current setup:

>An assertion used in this context is generally a short-lived representation of the authorization grant, and authorization servers SHOULD NOT issue access tokens with a lifetime that exceeds the validity period of the assertion by a significant period. In practice, that will usually mean that **refresh tokens are not issued in response to assertion grant requests**, and access tokens will be issued with a reasonably short lifetime.  Clients can refresh an expired access token by requesting a new one using the same assertion, if it is still valid, or with a new assertion.

(emphasis mine)

**Comment by StarWar** [comment]
@NuckChorris  Thanks for responding. So I should not use refresh tokens and instead use assertion which is in my case is facebook access token to create new access token. Wouldn't it be inefficient? If it's fine to use assertion then I would do that. Also I think it's faster to use refresh token instead of assertion. Because I had to query facebook at back end and retrieve user. 

As of now I stopped using refresh token and implemented via assertion. Is that the best approach in my case.

**Comment by NuckChorris** [comment]
I can't speak for the authors of the specification, but my interpretation is that you need to retrieve a new facebook token whenever your assertion token expires, and that the assertion token should not last longer than the facebook token.

Presumably this is to protect against the situation where an assertion is time-sensitive, but I do wonder if it actually matters in reality: would there be any negative to ignoring that paragraph of the spec and issuing tokens for a longer lifespan?

That being said, I'm not sure what this issue is about.  Is it refresh tokens or normal tokens?  Is it that the flow isn't issuing refresh tokens?  Is it the other way around?  I'm just not sure what your issue is

**Comment by StarWar** [comment]
@NuckChorris As of now I've stopped issuing refresh tokens and instead started using assertion to get new access token each item. I'm using fb sdk on my client side so it should give me a fresh token and using it works. It's just that refresh tokens aren't secure if someone gets them, they can indefinitely use it to issue new access tokens. I followed your suggestion and stopped issuing refresh tokens, since I'm using refresh tokens. If refresh tokens did require client_id and client_secret that would've made it really good solution in my case.

**Comment by ebosantos** [comment]
@StarWar Could you please share the source code of your solution? At least the initializers/doorkeeper.rb.

Tks

**Comment by matfiz** [comment]
@NuckChorris @StarWar just to clarify what was the motivation of the authors of the specification. The assertion token should not exceed lifespan of facebook token, because only this way if you revoke access on facebook side, then you can be sure that the access to 3rd party apps will be also revoked. If refresh token would be used, then potential fraud is possible. I agree this is less efficient in terms of numbers of requests needed to obtain new assertion token, but safety first!

**Comment by johanvdlaak** [comment]
To disable refresh_tokens for the assertion flow you could use the following monkey patch (located in config/initializers/monkey_doorkeerper_assertion.rb):

```ruby
module Doorkeeper
  module Request
    class Assertion < Strategy

      def request
        @request ||= OAuth::PasswordAccessTokenRequest.new(
          doorkeerper_config_patch,
          client,
          resource_owner_from_assertion,
          parameters
        )
      end

      private

        def doorkeerper_config_patch
          config = Doorkeeper.configuration.dup
          config.instance_variable_set(:'@refresh_token_enabled', false)
          config
        end

    end
  end
end
```
